CREATE SCHEMA mech;

CREATE TABLE mech.departamentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    descricao text NOT NULL,
    CONSTRAINT pk_departamentos PRIMARY KEY (id)
);

CREATE TABLE mech.especialidades (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    CONSTRAINT pk_especialidades PRIMARY KEY (id)
);

CREATE TABLE mech.estados (
    id text NOT NULL,
    nome text NOT NULL,
    CONSTRAINT pk_estados PRIMARY KEY (id)
);

CREATE TABLE mech.generos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    CONSTRAINT pk_generos PRIMARY KEY (id)
);

CREATE TABLE mech.medicos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    crm text NOT NULL,
    CONSTRAINT pk_medicos PRIMARY KEY (id)
);

CREATE TABLE mech.tipos_de_quarto (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    CONSTRAINT pk_tipos_de_quarto PRIMARY KEY (id)
);

CREATE TABLE mech.cidades (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    estado_id text NOT NULL,
    nome text NOT NULL,
    CONSTRAINT pk_cidades PRIMARY KEY (id),
    CONSTRAINT fk_cidades_estado_estado_id FOREIGN KEY (estado_id) REFERENCES mech.estados (id) ON DELETE CASCADE
);

CREATE TABLE mech.departamentos__medicos (
    departamento_id bigint NOT NULL,
    medico_id bigint NOT NULL,
    CONSTRAINT pk_departamentos__medicos PRIMARY KEY (departamento_id, medico_id),
    CONSTRAINT fk_departamentos__medicos_departamentos_departamento_id FOREIGN KEY (departamento_id) REFERENCES mech.departamentos (id) ON DELETE CASCADE,
    CONSTRAINT fk_departamentos__medicos_medico_medico_id FOREIGN KEY (medico_id) REFERENCES mech.medicos (id) ON DELETE CASCADE
);

CREATE TABLE mech.medicos__especialidades (
    medico_id bigint NOT NULL,
    especialidade_id bigint NOT NULL,
    CONSTRAINT pk_medicos__especialidades PRIMARY KEY (medico_id, especialidade_id),
    CONSTRAINT fk_medicos__especialidades_especialidades_especialidade_id FOREIGN KEY (especialidade_id) REFERENCES mech.especialidades (id) ON DELETE CASCADE,
    CONSTRAINT fk_medicos__especialidades_medicos_medico_id FOREIGN KEY (medico_id) REFERENCES mech.medicos (id) ON DELETE CASCADE
);

CREATE TABLE mech.quartos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo_de_quarto_id bigint NOT NULL,
    esta_ocupado boolean NOT NULL,
    CONSTRAINT pk_quartos PRIMARY KEY (id),
    CONSTRAINT fk_quartos_tipo_de_quarto_tipo_de_quarto_id FOREIGN KEY (tipo_de_quarto_id) REFERENCES mech.tipos_de_quarto (id) ON DELETE CASCADE
);

CREATE TABLE mech.enderecos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cidade_id bigint NOT NULL,
    cep text NOT NULL,
    rua text NOT NULL,
    bairro text NOT NULL,
    CONSTRAINT pk_enderecos PRIMARY KEY (id),
    CONSTRAINT fk_enderecos_cidades_cidade_id FOREIGN KEY (cidade_id) REFERENCES mech.cidades (id) ON DELETE CASCADE
);

CREATE TABLE mech.pacientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    genero_id bigint NOT NULL,
    endereco_id bigint NOT NULL,
    cpf text NOT NULL,
    cns text NOT NULL,
    nome text NOT NULL,
    data_de_nascimento date NOT NULL,
    CONSTRAINT pk_pacientes PRIMARY KEY (id),
    CONSTRAINT fk_pacientes_enderecos_endereco_id FOREIGN KEY (endereco_id) REFERENCES mech.enderecos (id) ON DELETE CASCADE,
    CONSTRAINT fk_pacientes_generos_genero_id FOREIGN KEY (genero_id) REFERENCES mech.generos (id) ON DELETE CASCADE
);

CREATE TABLE mech.estadias (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    paciente_id bigint NOT NULL,
    medico_id bigint NOT NULL,
    quarto_id bigint NOT NULL,
    motivo_da_admissao text NOT NULL,
    data_da_admissao timestamp without time zone NOT NULL,
    data_da_alta timestamp without time zone NOT NULL,
    CONSTRAINT pk_estadias PRIMARY KEY (id),
    CONSTRAINT fk_estadias_medicos_medico_id FOREIGN KEY (medico_id) REFERENCES mech.medicos (id) ON DELETE CASCADE,
    CONSTRAINT fk_estadias_paciente_paciente_id FOREIGN KEY (paciente_id) REFERENCES mech.pacientes (id) ON DELETE CASCADE,
    CONSTRAINT fk_estadias_quartos_quarto_id FOREIGN KEY (quarto_id) REFERENCES mech.quartos (id) ON DELETE CASCADE
);

CREATE INDEX ix_cidades_estado_id ON mech.cidades (estado_id);
CREATE INDEX ix_departamentos__medicos_medico_id ON mech.departamentos__medicos (medico_id);
CREATE INDEX ix_enderecos_cidade_id ON mech.enderecos (cidade_id);
CREATE INDEX ix_estadias_medico_id ON mech.estadias (medico_id);
CREATE INDEX ix_estadias_paciente_id ON mech.estadias (paciente_id);
CREATE INDEX ix_estadias_quarto_id ON mech.estadias (quarto_id);
CREATE INDEX ix_medicos__especialidades_especialidade_id ON mech.medicos__especialidades (especialidade_id);
CREATE INDEX ix_pacientes_endereco_id ON mech.pacientes (endereco_id);
CREATE INDEX ix_pacientes_genero_id ON mech.pacientes (genero_id);
CREATE INDEX ix_quartos_tipo_de_quarto_id ON mech.quartos (tipo_de_quarto_id);
