services:
  postgres_pi:
    image: postgres:17.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && psql -U postgres -d postgres -c 'SELECT 1;'"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_pi:/var/lib/postgresql/data
      - ./BackEnd/s.sql:/docker-entrypoint-initdb.d/s.sql
    ports:
      - "5432:5432"
    networks:
      - app-pi
    restart: unless-stopped

  backend1_pi:
    build:
      context: .
      dockerfile: Dockerfile.back
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__DefaultConnection=Host=postgres_pi;Database=postgres;Username=postgres;Password=postgres;Pooling=true;MinPoolSize=1;MaxPoolSize=10
    depends_on:
      postgres_pi:
        condition: service_healthy
    networks:
      - app-pi
    ports:
      - "5001:5001"
    restart: unless-stopped

  backend2_pi:
    build:
      context: .
      dockerfile: Dockerfile.back
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionStrings__DefaultConnection=Host=postgres_pi;Database=postgres;Username=postgres;Password=postgres;Pooling=true;MinPoolSize=1;MaxPoolSize=10
    depends_on:
      postgres_pi:
        condition: service_healthy
    networks:
      - app-pi
    ports: 
      - "5002:5002"
    restart: unless-stopped

  backend3_pi:
    build:
      context: .
      dockerfile: Dockerfile.back
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - ConnectionStrings__DefaultConnection=Host=postgres_pi;Database=postgres;Username=postgres;Password=postgres;Pooling=true;MinPoolSize=1;MaxPoolSize=10
    depends_on:
      postgres_pi:
        condition: service_healthy
    networks:
      - app-pi
    ports:
      - "5003:5003"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1_pi
      - backend2_pi
      - backend3_pi
    networks:
      - app-pi
    restart: unless-stopped

volumes:
  postgres_data_pi:

networks:
  app-pi:
    driver: bridge
