FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./BackEnd/BackEnd.csproj"
RUN dotnet publish "./BackEnd/BackEnd.csproj" -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app ./

EXPOSE 5001

ENTRYPOINT [ "dotnet", "BackEnd.dll" ]
