CREATE SCHEMA mech;

CREATE TABLE mech.medicos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    crm text NOT NULL,
    especialidade text NOT NULL,
    CONSTRAINT pk_medicos PRIMARY KEY (id)
);
